Repository pypa/virtualenv, pull requests merged in 2020-02, with the labels that each got.

#1536 README is now markdown instead of reStructuredText
  README.md
  README.rst
  azure-pipelines.yml
  docs/changelog/1531.doc.rst
  setup.cfg
  tox.ini
Labels: enhancement

#1534 pyproject.toml for version generation
  pyproject.toml
  setup.py
Labels: enhancement

#1535 Stable order in pyenv.cfg, include-system-site-packages only for ref
  docs/changelog/1535.bugfix.rst
  src/virtualenv/create/creator.py
  src/virtualenv/create/via_global_ref/api.py
  src/virtualenv/pyenv_cfg.py
Labels: enhancement

#1539 update release process to include zipapp
  azure-pipelines.yml
  tox.ini
Labels: enhancement

#1546 release 20.0.0
  azure-pipelines.yml
  docs/changelog.rst
  docs/cli_interface.rst
  docs/development.rst
  docs/index.rst
  docs/installation.rst
  docs/user_guide.rst
  pyproject.toml
  setup.cfg
  tox.ini
Labels: enhancement

#1550 fix system executable discovery
  azure-pipelines.yml
  docs/changelog/1552.bugfix.rst
  docs/changelog/1553.bugfix.rst
  src/virtualenv/create/creator.py
  src/virtualenv/create/via_global_ref/builtin/python2/python2.py
  src/virtualenv/discovery/cached_py_info.py
  src/virtualenv/discovery/py_info.py
  src/virtualenv/util/path/_pathlib/via_os_path.py
  tests/unit/create/test_creator.py
Labels: enhancement

#1548 Documentation theme updates
  docs/_static/custom.css
  docs/changelog/1548.doc.rst
Labels: docs

#1574 only info if during discovery fail to query a executable
  docs/changelog/1574.bugfix.rst
  src/virtualenv/discovery/cached_py_info.py
Labels: enhancement

#1575 respect --copies for app-data
  docs/changelog/1575.bugfix.rst
  src/virtualenv/seed/via_app_data/via_app_data.py
Labels: enhancement

#1573 on exe discovery ignore incorrect interpreters, also try in the candidate folders platform binary
  docs/changelog/1545.bugfix.rst
  src/virtualenv/discovery/py_info.py
  tests/unit/discovery/py_info/test_py_info.py
Labels: enhancement

#1572 add option to view failure stacktraces
  docs/changelog/1572.feature.rst
  src/virtualenv/__main__.py
  src/virtualenv/config/cli/parser.py
  src/virtualenv/run/__init__.py
  tests/conftest.py
  tests/unit/create/test_creator.py
Labels: enhancement

#1571 avoid copying the stats with copytree
  docs/changelog/1561.bugfix.rst
  src/virtualenv/seed/via_app_data/pip_install/base.py
  src/virtualenv/seed/via_app_data/pip_install/copy.py
  src/virtualenv/util/path/__init__.py
  src/virtualenv/util/path/_sync.py
  tests/integration/test_zipapp.py
Labels: enhancement

#1578 app-data copies by default
  docs/changelog/1557.feature.rst
  docs/changelog/1575.bugfix.rst
  src/virtualenv/seed/via_app_data/via_app_data.py
  tests/unit/seed/test_boostrap_link_via_app_data.py
Labels: enhancement

#1579 support long path names for the app-data seeder generates console entry points
  docs/changelog/997.bugfix.rst
  setup.cfg
  src/virtualenv/seed/via_app_data/pip_install/base.py
  tests/unit/create/test_creator.py
Labels: enhancement

#1580 release 20.0.2
  docs/changelog.rst
  docs/changelog/1545.bugfix.rst
  docs/changelog/1547.doc.rst
  docs/changelog/1548.doc.rst
  docs/changelog/1557.feature.rst
  docs/changelog/1559.feature.rst
  docs/changelog/1561.bugfix.rst
  docs/changelog/1568.feature.rst
  docs/changelog/1572.feature.rst
  docs/changelog/1574.bugfix.rst
  docs/changelog/1575.bugfix.rst
  docs/changelog/997.bugfix.rst
  tests/unit/create/test_creator.py
Labels: enhancement

#1588 Fix Python 2 Apple framework builds not isolated from global site packages
  docs/changelog/1561.bugfix.rst
  src/virtualenv/create/via_global_ref/builtin/python2/site.py
  tests/unit/create/test_creator.py
Labels: enhancement

#1591 Fix app-data injected .dist-info.virtualenv breaks importlib.metadata
  docs/changelog/1589.bugfix.rst
  src/virtualenv/seed/via_app_data/pip_install/base.py
Labels: bugfix

#1593 update the issue template to virtualenv 20+
  .github/ISSUE_TEMPLATE.md
  .github/stale.yml
Labels: enhancement

#1590 fix python discovery with non resolved prefix paths
  docs/changelog/1583.bugfix.rst
  src/virtualenv/__main__.py
  src/virtualenv/discovery/py_info.py
  src/virtualenv/run/__init__.py
Labels: enhancement

#1592 expose and document programmatic API
  docs/changelog/1585.bugfix.rst
  docs/changelog/1585.doc.rst
  docs/render_cli.py
  docs/user_guide.rst
  src/virtualenv/__init__.py
  src/virtualenv/__main__.py
  src/virtualenv/config/ini.py
  src/virtualenv/run/__init__.py
  src/virtualenv/session.py
  tests/conftest.py
  tests/integration/test_zipapp.py
  tests/unit/activation/conftest.py
  tests/unit/create/conftest.py
  tests/unit/create/test_creator.py
  tests/unit/create/test_interpreters.py
  tests/unit/seed/test_boostrap_link_via_app_data.py
  tests/unit/seed/test_extra_install.py
  tests/unit/seed/test_pip_invoke.py
  tests/unit/test_run.py
Labels: enhancement

#1595 release 20.0.3
  docs/changelog.rst
  docs/changelog/1561.bugfix.rst
  docs/changelog/1583.bugfix.rst
  docs/changelog/1585.bugfix.rst
  docs/changelog/1585.doc.rst
  docs/changelog/1589.bugfix.rst
Labels: enhancement

#1623 Add Gitter Badges
  README.md
  docs/index.rst
Labels: enhancement

#1625 release 20.0.4
  docs/changelog.rst
  docs/changelog/1582.bugfix.rst
  docs/changelog/1596.feature.rst
  docs/changelog/1606.bugfix.rst
Labels: enhancement

#1628 Better error message when build dependencies not satisfied
  docs/changelog/1621.feature.rst
  pyproject.toml
  setup.cfg
  setup.py
Labels: enhancement

#1641 macOs Python 2 Framework support
  azure-pipelines.yml
  docs/changelog/1561.bugfix.rst
  docs/changelog/1641.feature.rst
  setup.cfg
  src/virtualenv/__main__.py
  src/virtualenv/create/via_global_ref/builtin/cpython/cpython2.py
  src/virtualenv/create/via_global_ref/builtin/cpython/mac_os.py
  src/virtualenv/create/via_global_ref/builtin/python2/python2.py
  src/virtualenv/create/via_global_ref/builtin/python2/site.py
  src/virtualenv/create/via_global_ref/builtin/ref.py
  src/virtualenv/discovery/py_info.py
  src/virtualenv/seed/embed/base_embed.py
  src/virtualenv/seed/via_app_data/via_app_data.py
  tests/unit/create/test_creator.py
  tests/unit/discovery/py_info/test_py_info.py
Labels: enhancement

#1650 release 20.0.5
  docs/changelog.rst
  docs/changelog/1561.bugfix.rst
  docs/changelog/1612.feature.rst
  docs/changelog/1614.bugfix.rst
  docs/changelog/1621.feature.rst
  docs/changelog/1624.bugfix.rst
  docs/changelog/1641.feature.rst
  docs/changelog/1643.bugfix.rst
  src/virtualenv/create/via_global_ref/builtin/cpython/cpython2.py
Labels: enhancement

#1653 Fix global site package always being added with bundled macOs python framework builds
  docs/changelog/1561.bugfix.rst
  src/virtualenv/create/via_global_ref/builtin/cpython/mac_os.py
  src/virtualenv/create/via_global_ref/builtin/python2/python2.py
  src/virtualenv/create/via_global_ref/builtin/python2/site.py
Labels: enhancement

#1655 Fix generated scripts use host version info rather than target
  docs/changelog/1600.bugfix.rst
  src/virtualenv/seed/via_app_data/pip_install/base.py
  src/virtualenv/seed/via_app_data/via_app_data.py
  tests/unit/create/test_creator.py
Labels: enhancement

#1656 fix pypy2 builtins are imported as stdlib modules
  docs/changelog/1652.bugfix.rst
  src/virtualenv/create/via_global_ref/builtin/pypy/pypy2.py
  src/virtualenv/create/via_global_ref/builtin/python2/python2.py
  src/virtualenv/create/via_global_ref/builtin/python2/site.py
  src/virtualenv/seed/via_app_data/pip_install/base.py
Labels: bug

#1657 Ensure distutils configuration values do not escape virtual environment
  setup.py
  src/virtualenv/create/via_global_ref/_distutils_patch_virtualenv.py
  src/virtualenv/create/via_global_ref/api.py
  src/virtualenv/create/via_global_ref/builtin/via_global_self_do.py
  src/virtualenv/create/via_global_ref/venv.py
  tests/unit/create/console_app/demo/__init__.py
  tests/unit/create/console_app/demo/__main__.py
  tests/unit/create/console_app/setup.cfg
  tests/unit/create/console_app/setup.py
  tests/unit/create/test_creator.py
  tests/unit/seed/test_boostrap_link_via_app_data.py
Labels: enhancement

#1662 update issue template, add contributing
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#1664 Accept python self-referencing python executables
  .dockerignore
  docs/changelog/1632.bugfix.rst
  src/virtualenv/discovery/py_info.py
Labels: enhancement

#1666 fix relative zipapp paths on UNIX - release 20.0.6
  docs/changelog.rst
  docs/changelog/1561.bugfix.rst
  docs/changelog/1600.bugfix.rst
  docs/changelog/1632.bugfix.rst
  docs/changelog/1640.bugfix.rst
  docs/changelog/1652.bugfix.rst
  docs/changelog/1660.bugfix.rst
  src/virtualenv/util/zipapp.py
Labels: enhancement

#1671 Disable distutils fixup for python 3
  docs/changelog/1669.bugfix.rst
  setup.py
  src/virtualenv/create/via_global_ref/api.py
  tests/unit/create/test_creator.py
Labels: enhancement

#1676 Fix list configuration value parsing
  docs/changelog/1674.bugfix.rst
  src/virtualenv/config/cli/parser.py
  src/virtualenv/config/convert.py
  tests/unit/config/test_env_var.py
Labels: enhancement
